name: Build Debug
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  BuildDebug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
            # - name: Signing properties
            #   env:
            #     SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
            #     SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
            #     SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            #   run: |
            #     touch signing.properties
            #     echo keystore.password="$SIGNING_STORE_PASSWORD" > signing.properties
            #     echo key.alias="$SIGNING_KEY_ALIAS" >> signing.properties
            #     echo key.password="$SIGNING_KEY_PASSWORD" >> signing.properties

      #     echo "cat signing.properties"
      #     cat signing.properties

      - name: Build
        if: success()
        run: |
          ./gradlew: --no-daemon common:assembleRelease
          ./gradlew: --no-daemon core:assembleRelease
          ./gradlew: --no-daemon hideapi:assembleRelease
          ./gradlew: --no-daemon service:assembleRelease


      - name: Upload Aritfact (common)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (universal)
          path: |
            common/build/outputs/aar/*.aar

      - name: Upload Aritfact (core)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (arm64-v8a)
          path: |
            core/build/outputs/aar/*.aar

      - name: Upload Aritfact (hideapi)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (armeabi-v7a)
          path: |
            hideapi/build/outputs/aar/*.aar

      - name: Upload Aritfact (service)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (x86_64)
          path: |
            service/build/outputs/aar/*.aar
